    
---
resources:
- name: repo
  type: git
  source:
    uri: https://github.com/spandanatv/question-service.git
    branch: master

jobs:
- name: build
  serial: true
  plan:
  - aggregate:
    - get: repo
  - task: build
    file: question-service/edp/build.yml
    params:
      PROJECT_TYPE: ((project-type))