    
---
resources:
- name: repo
  type: git
  source:
    uri: https://github.com/spandanatv/question-service.git
    branch: master
- name: deploy-cf
  type: cf
  source:
    api: http://api.system.biarca.com
    username: shukoora@vedams.com
    password: Vedams@1234
    organization: Biarca
    space: ipsum-dev
    skip_cert_check: true
jobs:
- name: build
  serial: true
  plan:
  - aggregate:
    - get: repo
  - task: build
    file: repo/edp/build.yml
  - put: deploy-cf
    params:
       manifest: question-service/manifest.yml
       path: artifacts/*.jar
       PROJECT_TYPE: GRADLE